name: weightechapp
description: "A Flutter implementation for WeighTech's sales app."
publish_to: 'none'
version: 0.2.6

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  carousel_slider: ^4.2.1
  desktop_drop: ^0.4.4
  feedback: ^3.1.0
  feedback_gitlab: ^3.0.0
  file_picker: ^5.2.10
  firebase_core: ^2.26.0
  firebase_database: ^10.5.2
  firebase_storage: ^11.6.8
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  google_fonts: ^6.2.1 
  image_picker: ^1.0.7
  mailto: ^2.0.0
  path_provider: ^2.1.2
  provider: ^6.1.2
  shortid: ^0.1.2
  simple_rich_text: ^2.0.49
  url_launcher: ^6.2.6
  feedback_github:
    git: 
      url: https://github.com/defuncart/feedback_github/
      ref: main
  http: ^1.2.1
  cloud_firestore: ^4.17.0
  cached_network_image: ^3.3.1
  flutter_cache_manager: ^3.3.2
  string_validator: ^1.0.2
  loading_animation_widget: ^1.2.1
  updat: ^1.3.2
  package_info_plus: ^8.0.0
  path: ^1.9.0
  logger: ^2.2.0
  firebase_auth: ^4.19.4
  file_saver: ^0.2.12
  fluent_ui: ^4.8.7
  fluentui_system_icons: ^1.1.238
  desktop_window: ^0.4.0
  window_manager: ^0.3.8
  animated_reorderable_list: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  msix: ^3.16.7

flutter:
  uses-material-design: true
  assets:
    - assets/weightech_logo.png
    - assets/weightech_logo_beta.png
    - assets/icon/wt_icon.ico
    - assets/skull.png
    - assets/skull2.gif
    - assets/skullbadge2.gif
    - assets/skullbadge_small.gif

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/icon/wt_icon.ico"
  windows:
    generate: true
    image_path: "assets/icon/wt_icon.ico"
    icon_size: 256