name: weightechapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  dotted_border: ^2.1.0
  firebase_core: ^2.26.0
  firebase_storage: ^11.6.8
  flutter:
    sdk: flutter
  flutter_markdown: ^0.6.22+1
  google_fonts: ^6.2.1 
  image_picker: ^1.0.7
  provider: ^6.1.2
  simple_rich_text: ^2.0.49
  video_player: ^2.8.3
  wakelock: ^0.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/weightech_logo.png
    - assets/product_images/