name: weightechapp
description: "A Flutter implementation for WeighTech's sales app."
publish_to: 'none'
version: 0.2.13

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  carousel_slider: ^5.0.0
  desktop_drop: ^0.5.0
  feedback: ^3.1.0
  file_picker: ^8.0.3
  firebase_core: ^3.0.0
  firebase_storage: ^12.0.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.0
  google_fonts: ^6.2.1 
  path_provider: ^2.1.2
  shortid: ^0.1.2
  simple_rich_text: ^2.0.49
  url_launcher: ^6.2.6
  window_manager: ^0.3.8
  feedback_github:
    git: 
      url: https://github.com/defuncart/feedback_github/
      ref: main
  http: ^1.2.1
  cloud_firestore: ^5.0.0
  cached_network_image: ^3.3.1
  flutter_cache_manager: ^3.3.2
  string_validator: ^1.0.2
  loading_animation_widget: ^1.2.1
  updat: ^1.3.2
  package_info_plus: ^8.0.0
  path: ^1.9.0
  logger: ^2.2.0
  firebase_auth: ^5.0.0
  retry: ^3.1.2
  internet_connection_checker_plus: ^2.3.0
  media_kit: ^1.1.10+1
  media_kit_video: ^1.2.4
  media_kit_libs_video: ^1.0.4
  mime: ^1.0.5
  fluent_ui: ^4.9.0
  fluentui_system_icons: ^1.1.251
  flutter_fancy_tree_view: ^1.6.0
  non_uniform_border: ^1.0.0
  archive: ^3.6.1
  file_saver: ^0.2.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/weightech_logo.png
    - assets/weightech_logo_beta.png
    - assets/icon/wt_icon.ico
    - assets/skullanimation_v2.gif
    - assets/skull2.gif
    - assets/skullbadge2.gif
    - assets/skullbadge_small.gif

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/icon/wt_icon.ico"
  windows:
    generate: true
    image_path: "assets/icon/wt_icon.ico"
    icon_size: 256