name: weightechapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  firebase_core: ^2.26.0
  firebase_storage: ^11.6.8
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1 
  wakelock: ^0.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/weightech_logo.png
    - assets/product_images/