name: weightechapp
description: "Android implementation for WeighTech's sales app."
publish_to: 'none'
version: 0.1.3+2

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  carousel_slider: ^5.0.0
  firebase_core: ^3.6.0
  firebase_database: ^11.1.4
  firebase_storage: ^12.3.2
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1 
  path_provider: ^2.1.2
  provider: ^6.1.2
  simple_rich_text: ^2.0.49
  http: ^1.2.1
  cached_network_image: ^3.3.1
  flutter_cache_manager: ^3.3.2
  updat: ^1.3.2
  package_info_plus: ^8.0.0
  path: ^1.9.0
  logger: ^2.2.0
  shortid: ^0.1.2
  string_validator: ^1.0.2
  file_saver: ^0.2.12
  media_kit: ^1.1.10+1
  media_kit_video: ^1.2.4
  media_kit_libs_video: ^1.0.4
  internet_connection_checker_plus: ^2.3.0
  cloud_firestore: ^5.4.3
  firebase_auth: ^5.3.1
  retry: ^3.1.2
  loading_animation_widget: ^1.2.1
  wakelock_plus: ^1.2.5
  flutter_archive: ^6.0.3
  upgrader: ^11.2.0
  apivideo_player: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: 0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/weightech_logo.png
    - assets/weightech_logo_beta.png
    - assets/icon/wt_icon.ico
    - assets/skullanimation_v2.gif
    - assets/skullanimation_v2.gif
    - assets/skull2.gif
    - assets/skullbadge2.gif
    - assets/skullbadge_small.gif

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/icon/android_icon-02.png"
  windows:
    generate: true
    image_path: "assets/icon/wt_icon.ico"
    icon_size: 256