// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaKfG95R_liIPQBivxLcSa9MaZg9LutuM',
    appId: '1:863473899531:web:87ff071f243d5903c30f0e',
    messagingSenderId: '863473899531',
    projectId: 'weightechapp',
    authDomain: 'weightechapp.firebaseapp.com',
    databaseURL: 'https://weightechapp-default-rtdb.firebaseio.com',
    storageBucket: 'weightechapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCd91NmsCYUNm3TyGIF7PojhsEkGB6SQGc',
    appId: '1:863473899531:android:619f57ac91bfcf7ac30f0e',
    messagingSenderId: '863473899531',
    projectId: 'weightechapp',
    databaseURL: 'https://weightechapp-default-rtdb.firebaseio.com',
    storageBucket: 'weightechapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaHqsjjTShg_F2kj-IZ5jACrqBcSkzKJU',
    appId: '1:863473899531:ios:c39348d62c71891cc30f0e',
    messagingSenderId: '863473899531',
    projectId: 'weightechapp',
    databaseURL: 'https://weightechapp-default-rtdb.firebaseio.com',
    storageBucket: 'weightechapp.appspot.com',
    iosBundleId: 'com.jtull.weightechapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaHqsjjTShg_F2kj-IZ5jACrqBcSkzKJU',
    appId: '1:863473899531:ios:c39348d62c71891cc30f0e',
    messagingSenderId: '863473899531',
    projectId: 'weightechapp',
    databaseURL: 'https://weightechapp-default-rtdb.firebaseio.com',
    storageBucket: 'weightechapp.appspot.com',
    iosBundleId: 'com.jtull.weightechapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaKfG95R_liIPQBivxLcSa9MaZg9LutuM',
    appId: '1:863473899531:web:663efbfa81990adac30f0e',
    messagingSenderId: '863473899531',
    projectId: 'weightechapp',
    authDomain: 'weightechapp.firebaseapp.com',
    databaseURL: 'https://weightechapp-default-rtdb.firebaseio.com',
    storageBucket: 'weightechapp.appspot.com',
  );

}